toucan/invitations/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView

from .views import InvitationAcceptedView, InviteToOrgView, RequestInvitationFormView


urlpatterns = [
    url(
        r'verify/(?P<secret_key>\w+)/$',
        InvitationAcceptedView.as_view(),
        name='accept_invitation'
    ),
    url(
        r'(?P<organisation_id>\d+)/invite/',
        InviteToOrgView.as_view(),
        name='invite_to_org'
    ),
    url(
        r'^request/',
        include([
            url(r'^$',
                RequestInvitationFormView.as_view(),
                name='request_invitation_form'
            ),
            url(
                r'^sent/$',
                TemplateView.as_view(template_name='invitations/request_access/contact_form_sent.html'),
                name='request_invitation_form_sent'
            )
        ])
    )
]

toucan/organisations/urls.py
from django.conf.urls import url, include

from .views import OrganisationDetail, OrganisationEdit, LocationCreate, LocationEdit, LocationDelete

app_name = 'organisations'

urlpatterns = [
    url(r'^$', OrganisationDetail.as_view(), name='detail'),
    url(r'^edit/$', OrganisationEdit.as_view(), name='edit'),
    url(r'^locations/', include([
        url(r'^add/$', LocationCreate.as_view(), name='add'),
        url(r'^(?P<pk>\d+)/$', LocationEdit.as_view(), name='edit'),
        url(r'^(?P<pk>\d+)/delete/$', LocationDelete.as_view(), name='delete')

    ], namespace='locations'))
]

toucan/user_profile/urls.py
from django.conf.urls import url
from .views import PersonalProfile, NotificationEditView, NotificationCreate, PublicProfile, \
    UpdatePhoneNumber, NotificationDeleteView, UpdateMentionNotificationSettingsView

urlpatterns = [
    url(r'^profile/(?P<username>[\w.@+-]+)/$', PublicProfile.as_view(), name='public_profile'),
    url(r'^$', PersonalProfile.as_view(), name='personal_profile'),
    url(r'^edit/$', UpdateMentionNotificationSettingsView.as_view(), name='update_profile'),
    url(r'^edit/phone/$', UpdatePhoneNumber.as_view(), name='update_phone'),
    url(r'^notifications/add/$', NotificationCreate.as_view(), name='notification_create'),
    url(r'^notifications/(?P<notification_id>\d+)/$', NotificationEditView.as_view(), name='notification_edit'),
    url(r'^notifications/(?P<notification_id>\d+)/delete/$', NotificationDeleteView.as_view(), name='notification_delete')
]

toucan_conf/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from toucan.invitations.views import InvitedSignupView
from toucan.issues.views import HomeView
from toucan.utils.views import MultiTemplateView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # these next 2 lines are important!
    url(r'^accounts/signup/', InvitedSignupView.as_view(), name='account_signup'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api/', include('toucan.api.urls')),
    url(r'^toucan/', include([
        url(r'^organisation/', include('toucan.organisations.urls', 'organisations')),
        url(r'^invitations/', include('toucan.invitations.urls')),
        url(r'^issues/', include('toucan.issues.urls', 'issue_app')),
        url(r'^profile/', include('toucan.user_profile.urls', 'user_profile')),
        url(r'^help/', include('toucan.help.urls', 'help'))
    ])),
]


if settings.DEBUG:

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

    import debug_toolbar

    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

    from toucan.notifications.debug import generate_notifications
    urlpatterns += [
        url(r'^__generate_notifications__/$', generate_notifications, name='generate_notifications')
    ]



class RedirectAuthenticatedUsers(MultiTemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return HttpResponseRedirect(reverse('home'))
        return super().get(request, *args, **kwargs)


urlpatterns += [
    url(r'^map/', include([
        # this is needed for reversing the issue url in the notifications
        url(r'^issue/(?P<issue_id>\d+)', HomeView.as_view(), name='home_issue'),
        url(r'', HomeView.as_view(), name='home'),  # => Single Page App
    ])),
    url(r'^$', RedirectAuthenticatedUsers.as_view(
        template_names=[
            'toucan/index.html',
            'default/landing_page.html'
        ]),
        name='landing_page'),
]

toucan/user_profile/models.py
from django.conf import settings
from django.contrib.gis.db import models as gis_models
from django.db import models
from django.utils.translation import ugettext_lazy as _
from model_utils.choices import Choices
from model_utils.models import TimeStampedModel
from phonenumber_field.modelfields import PhoneNumberField

from ..issues.models import Issue, IssueType
from ..notifications.fields import NotificationTypeField
from ..organisations.models import Organisation

from toucan.utils.staticmap import get_url_for_geographic_notification


class Subscription(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='subscriptions')
    issue = models.ForeignKey(Issue)

    def __str__(self):
        return 'Subscription object %d' % self.pk

    class Meta:
        ordering = ('-created',)


class NotificationSettings(TimeStampedModel):
    '''
    The base model for any notification filters.

    Notifications can be filtered by the following criteria:
        - the issue type
        - the organisations that issued the issue
        - geographic information => defined by a point and a radius
    '''

    NOTIFICATION_TYPES = Choices(
        # ('sms', _('Text Message (SMS)')),
        ('email', _('Email'))
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='notifications_settings')
    notification_type = models.CharField(
        choices=NOTIFICATION_TYPES,
        default='email',
        max_length=20
    )

    issue_types = models.ManyToManyField(IssueType, blank=True, verbose_name=_('issue types'))

    organisations = models.ManyToManyField(
        Organisation,
        blank=True
    )

    point = gis_models.PointField(blank=False)
    point_radius = models.PositiveSmallIntegerField(
        default=2,
        verbose_name=_('radius in kilometers')
    )

    enabled = models.BooleanField(default=True)

    def get_preview_image_url(self):
        return get_url_for_geographic_notification(self)

    def send(self, issue):
        if self.notification_type == 'email':
            from .notifications.email import EmailNotification as Notification
        elif self.notification_type == 'sms':
            from .notifications.sms import SMSNotification as Notification

        notification = Notification(self, issue)
        return notification.send_issue_notification()

    def __str__(self):
        return 'Notification rule of user: %s' %(self.user.username)

    class Meta:
        ordering = ('-created',)


class Profile(models.Model):

    user = models.OneToOneField(settings.AUTH_USER_MODEL)

    phone_number = PhoneNumberField(
        blank=True,
        verbose_name=_('phone number')
    )

    user_mention_notification = NotificationTypeField(
        blank=True,
        default='',
        verbose_name=_('Notification when mentioned')
    )

    org_mention_notification = NotificationTypeField(
        blank=True,
        default='',
        verbose_name=_('Notification when your organisation is mentioned')
    )

toucan/user_profile/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget

from ..organisations.models import Organisation
from .models import Profile, NotificationSettings
from allauth.account.forms import LoginForm


phone_number_help_text = _('Please enter your mobile phone number in international format. E.g. "+431234526"')


class BaseUserProfileSignupForm(forms.Form):

    def signup(self, request, user):
        # save phone number to profile
        profile, created = Profile.objects.get_or_create(
            user=user
        )



class UserProfileSignupForm(BaseUserProfileSignupForm):

    org = forms.ModelChoiceField(
        queryset=Organisation.objects.all(),
        label=_('Organisation'),
        help_text=_('You can become a member of an existing organisation now or create your own at a later point.'),
        required=False
    )

    def signup(self, request, user):
        super().signup(request, user)

        # if given add to organisation
        org = self.cleaned_data.get('org')
        if org:
            org.add_member(user)


class NotificationSettingsForm(forms.ModelForm):

    class Meta:
        model = NotificationSettings
        fields = [
            'point',
            'point_radius',
            'notification_type',
            'organisations',
            'issue_types',
        ]
        widgets = {
            'point': forms.HiddenInput
        }
        help_texts = {
            'organisations': _('Notifications can be filtered by Organisation (default: all).'),
            'issue_types': _('Filter by issue type (default: all).'),
            'notification_type': _('Choose how you want to be notified.')
        }
        error_messages = {
            'point': {
                'required': _('Please select a point from the map.')
            }
        }


class ToucanLoginForm(LoginForm):

    def get_initial_for_field(self, field, field_name):
        if field_name == 'remember':
            return True
        return super().get_initial_for_field(field, field_name)


class PhoneNumberUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = [
            'phone_number'
        ]

        help_texts = {
            'phone_number': phone_number_help_text
        }

toucan/user_profile/views.py
from django.views.generic import UpdateView, TemplateView, DetailView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.contrib.auth import get_user_model
from braces.views import FormValidMessageMixin

from ..organisations.models import Membership, Organisation
from .models import Profile, NotificationSettings
from .forms import NotificationSettingsForm, PhoneNumberUpdateForm


class PublicProfile(DetailView):
    model = get_user_model()
    slug_field = 'username'
    slug_url_kwarg = 'username'
    template_name = 'user_profile/public.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        memberships = Membership.objects\
                            .filter(user=self.object)\
                            .order_by('org__name')\
                            .select_related('org')
        ctx.update({
            'memberships': memberships,
        })
        return ctx


class PersonalProfile(LoginRequiredMixin, PublicProfile):

    template_name = 'user_profile/private.html'

    def get_object(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        try:
            profile = Profile.objects.get(user=self.object)
        except Profile.DoesNotExist:
            profile = None

        notification_settings = NotificationSettings.objects\
            .filter(user=self.object)\
            .prefetch_related('organisations', 'issue_types')

        ctx.update({
            'profile': profile,
            'notification_settings': notification_settings
        })
        return ctx


class UpdateMentionNotificationSettingsView(LoginRequiredMixin, FormValidMessageMixin, UpdateView):
    fields = [
        'user_mention_notification',
        'org_mention_notification'
    ]

    template_name = 'user_profile/edit_mention_settings.html'
    form_valid_message = _('Mention settings updated.')

    def get_success_url(self):
        return reverse(
            'user_profile:personal_profile',
        )

    def get_object(self, queryset=None):
        return Profile.objects.get_or_create(user=self.request.user)[0]


class UpdatePhoneNumber(LoginRequiredMixin, FormValidMessageMixin, UpdateView):

    template_name = 'user_profile/edit_phone.html'
    form_valid_message = _('Phone number updated.')
    form_class = PhoneNumberUpdateForm

    def get_success_url(self):
        return reverse(
            'user_profile:personal_profile',
        )

    def get_object(self, queryset=None):
        return Profile.objects.get_or_create(user=self.request.user)[0]

class NotificationCreate(LoginRequiredMixin, FormValidMessageMixin, CreateView):

    form_class = NotificationSettingsForm
    template_name = 'user_profile/notification/create.html'
    model = NotificationSettings
    form_valid_message = _('Notification settings updated.')

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['organisations'].queryset = Organisation.active.all()
        return form

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'user_profile:personal_profile',
        )

class BaseNotificationView(PermissionRequiredMixin):
    model = NotificationSettings
    pk_url_kwarg = 'notification_id'

    def has_permission(self):
        return self.request.user == self.get_object().user

    def get_success_url(self):
        return reverse(
            'user_profile:personal_profile',
        )


class NotificationEditView(BaseNotificationView, FormValidMessageMixin, UpdateView):
    form_class = NotificationSettingsForm
    template_name = 'user_profile/notification/edit.html'
    form_valid_message = _('Notification rule updated.')

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)
        form.fields['organisations'].queryset = Organisation.active.all()
        return form


class NotificationDeleteView(BaseNotificationView, FormValidMessageMixin, DeleteView):
    template_name = 'user_profile/notification/delete.html'
    form_valid_message = _('Notification rule deleted.')

toucan/user_profile/templates/user_profile/base.html
{% extends 'default/base.html' %}
{% block body-classes %}form-settings form-blue{% endblock %}
{% load i18n %}
{% block main %}

<div class="toucan-form">
  <div class="form-header-sticky">
    <a class="pull-right text-cancel" href="{% block close-link-href %}/{% endblock %}">
        {% block close-text %}
        {% trans 'Close' %}
        {% endblock %}
    </a>
    <h1 class="form-title">
      {% block profile-title %}
      {% trans 'Profile for' %} {{ user.username }}
      {% endblock %}
    </h1>
  </div>
  {% block profile-title-body %}{% endblock %}
  {% block content %}{% endblock content %}
</div>
{% endblock main %}

toucan/user_profile/templates/user_profile/edit.html
{% extends 'default/base.html' %}
{% block body-classes %}form-settings form-blue{% endblock %}
{% load i18n bootstrap3 %}
{% block main %}

<div class="toucan-form">
  <div class="form-header-sticky">
    <a href="/toucan/profile/" class="pull-right text-cancel">
      {% trans 'Cancel' %}
    </a>
    <h1 class="form-title">
      {% block profile-title %}
      {% trans 'Profile for' %} {{ user.username }}
      {% endblock %}
    </h1>
  </div>
  <form method="post" action="">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary btn-xs-block">
          {% trans 'Save' %}
      </button>
      {% endbuttons %}
  </form>
</div>
{% endblock main %}

toucan/user_profile/templates/user_profile/edit_mention_settings.html
{% extends './edit.html' %}
{% load i18n %}

{% block profile-title %}
{% trans 'Edit your mention notification settings' %}
{% endblock %}

toucan/user_profile/templates/user_profile/edit_phone.html
{% extends './edit.html' %}
{% load i18n %}

{% block profile-title %}
{% trans 'Edit your phone number' %}
{% endblock %}

toucan/user_profile/templates/user_profile/private.html
{% extends 'user_profile/public.html' %}

{% load i18n %}

{% block profile-title %}
    {% trans 'Your profile page' %}
{% endblock %}


{% block content %}

<div class="profile-section">
  <h2>{% trans 'Personal information' %}</h2>
  <div class="form-group form-group-setting">
    <div class="row">
      <div class="col-sm-4">
        <label>
          {% trans 'Email' %}
        </label>
      </div>
      <div class="col-sm-4">
        {{ user.email }}
      </div>
      <div class="col-sm-4">
        <a class="" href="{% url 'account_email' %}">
          Manage your email address
        </a>
      </div>
    </div>
  </div>
</div>

    <div class="profile-section">
      {{ block.super }}
    </div>

    <div class="profile-section">
      <h2>{% trans 'Mentioning settings' %}</h2>
      <div class="form-group form-group-setting">
        <div class="row">
          <div class="col-sm-8">
            {% trans 'Notification when mentioned' %}
            <p class="text-muted">
              somebody mentions you by typing @{{ user.username }}
            </p>
          </div>
          <div class="col-sm-4">
            {{ profile.get_user_mention_notification_display }}
          </div>
        </div>
      </div>
      <div class="form-group form-group-setting">
        <div class="row">
          <div class="col-sm-8">
            {% trans 'Notification when your organisation is mentioned' %}
            <p class="text-muted">
              somebody mentions your organisation by typing @{{ user.membership.org.short_name }}
            </p>
          </div>
          <div class="col-sm-4">
            {{ profile.get_org_mention_notification_display }}
          </div>
        </div>
      </div>
      <div class="form-group">
          <a class='btn btn-primary btn-sm' href="{% url 'user_profile:update_profile' %}">
              {% trans 'Change mentioning settings' %}
          </a>
      </div>

    </div>
    <div class="profile-section">
      <h2>Geographic notifications</h2>

      <p class="text-muted">
          You can configure Toucan to notify you of new issues within a defined geographic radius.
      </p>
      <p>
        <a class="btn btn-primary btn-sm" href="{% url 'user_profile:notification_create' %}">
          {% trans '+ Add notification rule' %}
        </a>
      </p>

      {% if notification_settings|length %}
        {% for ns in notification_settings%}
        <div class="notification">
          <div class="row">
            <div class="col-sm-3">
              <img class="notification-map" src="{{ ns.get_preview_image_url }}" alt="map" width="138" height="138"/>
            </div>
            <div class="col-sm-9">
              <p>
                {{ ns.created|date:'SHORT_DATETIME_FORMAT' }}
              </p>
              <p>
                <strong>
                  {% trans 'Issue types' %}
                </strong>
                {% for it in ns.issue_types.all %}
                <span class="badge badge-issue">{{ it.name }}</span>
                {% empty %}
                <span>{% trans 'all' %}</span>
                {% endfor %}
              </p>
              <p>
                <strong>
                  {% trans 'Organisations' %}
                </strong>
                {% for org in ns.organisations.all %}
                <span class="badge badge-member">{{ org.name }}</span>
                {% empty %}
                <span>{% trans 'all' %}</span>
                {% endfor %}

              </p>
              <p class="notification-controls">
                <a href="{% url 'user_profile:notification_edit' notification_id=ns.pk %}">
                  {% trans 'Edit' %}
                </a>
                <a class="text-danger notification-delete" href="{% url 'user_profile:notification_delete' notification_id=ns.pk %}">
                  {% trans 'Delete' %}
                </a>
              </p>
            </div>
          </div>
        </div>
          
          {% endfor %}
      {% else %}
      <div class="form-group">
      <p class="alert alert-info">
          {% blocktrans %}
              You have no notifications configured.
              Add your first notification rule to be notified when something happens around you.
          {% endblocktrans %}
      </p>
      </div>
      {% endif %}

      <div style="margin-bottom: 3em">
      </div>
    </div>

    {%  comment %}
    <h2>{% trans 'Subscriptions' %}</h2>
    <hr />
    {% with subscriptions=user.subscriptions.all %}
    {% if subscriptions|length %}
    <table class="table">
        <tbody>
        {% for subscription in  subscriptions %}
            <tr>
                <td>
                    {{ subscription.issue.title }}
                </td>
                <td>
                    {{ subscription.created }}
                </td>
            </tr>
        {% empty %}
            <tr>
                <td>
                    <span class="text-muted">
                        {% trans 'You have no active subscriptions at this time.' %}
                    </span>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p class="text-muted">
        {% blocktrans %}
            No active subscriptions. Subscriptions are always related to specific issues and are created interacting (commenting etc) with them.
        {% endblocktrans %}
        </p>
    {% endif %}
    {% endwith %}
    {% endcomment %}

{% endblock %}

toucan/user_profile/templates/user_profile/public.html
{% extends 'user_profile/base.html' %}
{% load i18n bootstrap3 imagekit %}
{% block content %}
<h2>{% trans 'Membership' %}</h2>
{% if memberships|length %}
<div class="form-group form-group-setting">
  {% if memberships|length > 1 %}
  <div class="row row-padded">
    <div class="col-xs-8">
      {% trans 'Organisation' %}
    </div>
    <div class="col-xs-4">
      {% trans 'Membership status' %}
    </div>
  </div>
  {% endif %} {% for membership in memberships %} {% with org=membership.org %}
  <div class="row row-padded">
    <div class="col-xs-8">
      <p>
        <label>
          {% trans 'Organisation' %}
        </label>
      </p>
      <a class="text-org" href="{% url 'organisations:detail' %}">
        {% if org.logo %}
            {% thumbnail '250x250' org.logo crop=0 %}
            <br />
        {% endif %}
        {{ org.name }}
      </a>
    </div>
    <div class="col-xs-4">

      {% if membership.active %}
      <span class="badge badge-success">
        {% trans 'Active' %}
      </span>
      {% else %}
      <span class="badge badge-default">
        {% trans 'Inactive' %}
      </span>
      {% endif %}
    </div>
  </div>
  {% endwith %} {% endfor %}
  </tbody>
</div>
{% else %}
<div class="form-group form-group-setting">
  <p class="text-muted">
    {% trans 'Not a member of an organisation.' %}
  </p>
</div>
{% endif %} {% endblock %}